import ArchitectLibrary
import Stevia
import UIKit

final class ImageDetailsView: UICodeView {
    // Views

    let blurBackgroundImageView = UIImageView()
    let blurEffectView = UIVisualEffectView(effect: UIBlurEffect(style: .regular))

    let scrollView = UIScrollView()
    let contentStackView = UIStackView(.vertical, alignment: .center, spacing: 16)

    let shadowImageView = UIView()
    let imageView = UIImageView()

    let imageInfoStack = UIStackView(.vertical, alignment: .leading)
    let categoryLabel = UILabel()
    let generatedByAILabel = UILabel()
    let ratingLabel = UILabel()
    let sourceLabel = UILabel()

    let artistInfoStack = UIStackView(.vertical, alignment: .leading)
    let artistTitleLabel = UILabel()
    let copyrightLabel = UILabel()
    let profileLabel = UILabel()

    let tagsInfoStack = UIStackView(.vertical, alignment: .leading)
    let tagsTitleLabel = UILabel()
//    let tagsCollection = UICollectionView(frame: .zero)

    let colorsInfoStack = UIStackView(.vertical, alignment: .leading)
    let colorsTitleLabel = UILabel()
//    let colorsCollection = UICollectionView(frame: .zero)

    let view = UIView()

    let loadingView = UIActivityIndicatorView()

    private var imageObserver: NSObjectProtocol?

    // Lifecycle

    override func initSubviews() {
        subviews(
            scrollView.subviews(
                contentStackView.addArrangedSubviews(
                    shadowImageView.subviews(
                        imageView
                    ),
                    imageInfoStack.addArrangedSubviews(
                        categoryLabel,
                        generatedByAILabel,
                        ratingLabel,
                        sourceLabel
                    ),
                    artistInfoStack.addArrangedSubviews(
                        artistTitleLabel,
                        copyrightLabel,
                        profileLabel
                    ),
                    tagsInfoStack.addArrangedSubviews(
                        tagsTitleLabel
                    ),
                    colorsInfoStack.addArrangedSubviews(
                        colorsTitleLabel
                    )
                )
            ),
            blurBackgroundImageView.subviews(
                blurEffectView
            )
        )
    }

    override func initLayout() {
        blurBackgroundImageView.fillContainer()
        blurEffectView.fillContainer()
        scrollView.fillContainer()
        contentStackView.top(16).bottom(0).fillHorizontally()
        contentStackView.Leading == safeAreaLayoutGuide.Leading
        contentStackView.Trailing == safeAreaLayoutGuide.Trailing

        shadowImageView.fillHorizontalMarginGuide(from: self)
        imageView.fillContainer()
        imageInfoStack.fillHorizontalMarginGuide(from: self)

        view.height(300)
    }

    override func initStyle() {
        clipsToBounds = true
        backgroundColor = .secondarySystemBackground
        blurBackgroundImageView.style { s in
            s.backgroundColor = .secondarySystemBackground
            s.contentMode = .scaleAspectFill
        }
        scrollView.style { s in
            s.alwaysBounceVertical = true
            s.layer.zPosition = 1
        }
        imageView.style { s in
            s.backgroundColor = .gray
            s.layer.masksToBounds = true
            s.layer.cornerRadius = 16
        }
        generatedByAILabel.style { s in
            s.text = "Generated by AI: Nope"
        }
    }

    func display(model: ImageItemDisplayModel) {
        categoryLabel.text = "Category: \(model.category)"
        ratingLabel.text = "Rating: \(model.rating)"
        sourceLabel.text = "Source: \(model.source ?? "not found")"
        copyrightLabel.text = model.copyright
        profileLabel.text = "\(model.username ?? "Profile"): \(model.profileURL ?? "url not found")"
        tagsTitleLabel.text = "Tags: " + model.tags.joined(separator: ", ")

        applyImageShadow(color: model.mainColor)
        imageView.aspectRatio(model.ratio)
        imageView.image = model.image
        blurBackgroundImageView.image = model.image

        imageObserver = NotificationCenter.default.addObserver(
            forName: model.idName, object: nil, queue: .main
        ) { [weak self, weak model] _ in
            self?.imageView.image = model?.image
            self?.blurBackgroundImageView.image = model?.image
        }
    }

    func applyImageShadow(color: UIColor?) {
        guard let shadowColor = color else { return }
        shadowImageView.style { s in
            let shadow = s.applyShadowObsever(
                color: shadowColor, alpha: 0.5, x: 0, y: 0,
                blur: 16, spread: 8, cornerRadius: 16
            )
            observers.append(shadow)
        }
    }
}
